[package]
name = "sia_nfs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
async-recursion = "1.1"
async-trait = "0.1"
bimap = "0.6"
chrono = "0.4"
clap = { version = "4.5", features = ["derive", "env"] }
futures = "0.3"
futures-util = "0.3"
itertools = "0.13"
moka = { version = "0.12", features = ["future"] }
nfsserve = "0.10"
parking_lot = "0.12"
renterd_client = { git = "https://github.com/rrauch/renterd_client.git", rev = "b6c3d08fc4e78b1304365a9a898f23b60c344cc5" }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite", "migrate", "chrono"] }
tokio = { version = "1.39", features = ["full"] }
tokio-util = "0.7"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2.5"

[build-dependencies]
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite", "migrate", "chrono"] }
tokio = { version = "1.39", features = ["full"] }

[patch.crates-io]
nfsserve = { git = "https://github.com/rrauch/nfsserve.git", rev = "57327866361b35c63829ee31cb0fdb4b9f07c08b" }