[package]
name = "sia_nfs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39", features = ["full"] }
tokio-util = "0.7"
anyhow = { version = "1.0", features = ["backtrace"] }
renterd_client = { path = "../renterd_client" }
chrono = "0.4"
futures = "0.3"
futures-util = "0.3"
bimap = "0.6"
itertools = "0.13"
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite", "migrate", "chrono"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
nfsserve = "0.10"
url = "2.5"
async-trait = "0.1"
async-recursion = "1.1"
arc-swap = "1.7"

[build-dependencies]
tokio = { version = "1.39", features = ["full"] }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite", "migrate", "chrono"] }
